### ISSUE TITLE
check_date vs. check_date:currency:XBT vs survey:date

### ISSUE THREAD

**Issue by iBobik** [teambtcmap/btcmap-data#4527]
Hi,
In the docs there is:
> If you visit a location and are able to pay with bitcoin it is best practice to update the survey:date, check_date, or check_date:currency:XBT tag yourself. 

I think most of OSM contributors will not try Bitcoin payment when using check_date and survey:date tag.

How about to require e.g. survey_date:currency:XBT for marking place as verified for Btcmap?
And maybe better clarify what is required. I suggest this:

- Tried to pay by Bitcoin in this place
- There is always employee who can accept Bitcoin. (In many businesse only owner can accept it and he is not there most of the time.)

**Comment by bubelov** [comment]
> I think most of OSM contributors will not try Bitcoin payment when using check_date and survey:date tag.

It happens, but we can't do anything about it since we can't prevent people from adding misinformation.

> How about to require e.g. survey_date:currency:XBT for marking place as verified for Btcmap?

This approach alienates BTC Map community from the general OSM community, and we're getting complaints about being uncooperative. That's why we're trying to use the general tags, where possible, which shows that we're also verifying the other tags and contributing to OSM.

**Comment by iBobik** [comment]
> we're getting complaints about being uncooperative.
Is there such discussion recorded somewhere?

Do they really complain about having survey_date:currency:XBT tag for confirmed BTC info? We can complain other OSM contributors does not check Bitcoin info when using generic survey:date, they does not consider this point relevant?

How to solve this need differently?

**Comment by iBobik** [comment]
For a context, I created [this app](https://mapa.berubitcoin.cz) with local data and verification focused on this - to promote only places with good paying experience, because mainstream hodlers often stop using Bitcoin for payments after a few unsuccessful tries.

I created it in a time before Btcmap.org was known here, so I build it with my own data. Now I would like to abandon custom data and use Btcmap/OSM, but I does not want to abandon data quality.

**Comment by bubelov** [comment]
> Do they really complain about having survey:date:currency:XBT tag for confirmed BTC info?

Yes, they complain about any scoped changes and verifying the rest of the tags is the preferred route since it shows that we're interested in maintaining our shared data and not just putting a Bitcoin tag here and there and calling it a day.

I guess we can recognize `survey:date:currency:XBT` tag, but only as an addition to the general `survey:date` tag, adding both of those tags won't break any rules and it shouldn't cause any issues or conflicts.

What's unclear is how we're going to visually differentiate those tags. Should we assume that `survey:date` is lying and ignore it, just because a few editors are using it wrong? There are many editors who're using this tag properly and they do check Bitcoin acceptance.

> I think most of OSM contributors will not try Bitcoin payment when using check_date and survey:date tag

Yea, most of them don't have any bitcoins to try that, but they can find a Bitcoin sign or ask the stuff about the available payment methods. You don't need to make a payment in order to bump check or survey date.

**Comment by bubelov** [comment]
This might be relevant: https://wiki.openstreetmap.org/wiki/Verifiability

**Comment by bubelov** [comment]
Feel free to re-open that issue if you have any other questions or feedback. Unfortunately, there is nothing we can do to make the data more reliable, since we don't control the data and anyone is free to add whatever they want with the tags. If you really want to keep the list of places which you personally verified or which were verified by your trusted circle, I would look into having a separate self-hosted verifications database which can be linked to OSM data. We're using this method too when we need to keep our own notes and metadata and when we don't want "outsiders" to be able to mess with it.
